Proyecto 3/Proyecto 3/Models/Parqueo.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Proyecto_3.Models
{
    public class Parqueo
    {
        [DisplayName("Número de Parqueo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo es requerido.")]
        public int Id { get; set; }

        [DisplayName("Nombre")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo es requerido.")]
        public string? Nombre { get; set; }

        [DisplayName("Cantidad máxima")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo es requerido.")]
        public int CantidadVehiculosMax { get; set; }

        [DisplayName("Hora de apertura")]
        [DataType(DataType.Time)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo es requerido.")]
        public DateTime HoraApertura { get; set; }

        [DisplayName("Hora de cierre")]
        [DataType(DataType.Time)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo es requerido.")]
        public DateTime HoraCierre { get; set; }

        [DisplayName("Tarifa (\t₡/hora )")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo es requerido.")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Favor ingresar solo números.")]
        [StringLength(5)]
        public string TarifaHora { get; set; }

        [DisplayName("Tarifa (\t₡/½hora )")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo es requerido.")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Favor ingresar solo números.")]
        [StringLength(5)]
        public string TarifaMedia { get; set; }
    }
}

Proyecto 3/Proyecto 3/Controllers/ParqueosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Proyecto_3.Models;
using Proyecto_3.Servicios;

namespace Proyecto_3.Controllers
{
    public class ParqueosController : Controller
    {
        private readonly IServicioParqueo _iservicioParqueo;

        public ParqueosController(IServicioParqueo iservicioParqueo)
        {
            _iservicioParqueo = iservicioParqueo;
        }


        /// ////////////////////////////////////////////////////////////////////////////////////////////////



        // GET: ParqueosController
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            List<Models.Parqueo> laLista;

            laLista = await _iservicioParqueo.Get();

            return View(laLista);
        }

        // GET: ParqueosController/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            List<Models.Parqueo> parqueos;

            parqueos = await _iservicioParqueo.Get();

            int nextId = 1;

            // Si hay parqueos en la lista, obtener el valor máximo de "Id" y agregar 1
            if (parqueos.Count > 0)
            {
                nextId = parqueos.Max(t => t.Id) + 1;
            }

            // Crear una nueva instancia de Parqueo con el próximo valor de "Id"
            Models.Parqueo nuevoParqueo = new Models.Parqueo
            {
                Id = nextId
            };

            return View(nuevoParqueo);
        }

        // POST: ParqueosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Models.Parqueo parqueo)
        {
            if (parqueo.HoraCierre <= parqueo.HoraApertura)
            {
                ModelState.AddModelError("HoraApertura", "La hora de apertura no puede ser mayor que la hora de cierre.");
            }

            if (int.Parse(parqueo.TarifaHora) <= int.Parse(parqueo.TarifaMedia))
            {
                ModelState.AddModelError("TarifaHora", "La tarifa por hora debe ser mayor que la tarifa por media hora.");
            }

            if (ModelState.IsValid)
            {
                await _iservicioParqueo.Crear(parqueo);

                try
                {
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }

        // GET: ParqueosController/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            var parqueo = await _iservicioParqueo.ObtenerParqueo(id);

            if (id != 0 && parqueo != null)
            {
                return View(parqueo);
            }

            else return RedirectToAction(nameof(Index));
        }

        // GET: ParqueosController/Edit/5
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            var parqueo = await _iservicioParqueo.ObtenerParqueo(id);

            return View(parqueo);
        }

        // POST: ParqueosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Models.Parqueo parqueo)
        {
            if (parqueo.HoraCierre <= parqueo.HoraApertura)
            {
                ModelState.AddModelError("HoraApertura", "La hora de apertura no puede ser mayor que la hora de cierre.");
            }

            if (int.Parse(parqueo.TarifaHora) <= int.Parse(parqueo.TarifaMedia))
            {
                ModelState.AddModelError("TarifaHora", "La tarifa por hora debe ser mayor que la tarifa por media hora.");
            }

            if (ModelState.IsValid)
            {
                await _iservicioParqueo.Put(id, parqueo);

                try
                {
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }

        // GET: ParqueosController/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            var parqueo = await _iservicioParqueo.ObtenerParqueo(id);

            return View(parqueo);
        }

        // POST: ParqueosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            await _iservicioParqueo.Delete(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Proyecto 3/Proyecto 3/Views/Parqueos/Create.cshtml
@model Proyecto_3.Models.Parqueo

@{
    ViewData["Title"] = "Create";
}

<h1 style="text-align:center">AGREGAR PARQUEO</h1>

<h2>Datos del Parqueo</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <strong>
                    @Html.DisplayNameFor(model => model.Id):
                </strong>
                @Html.DisplayFor(model => model.Id)
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="Nombre" class="control-label"></label>
                </strong>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="CantidadVehiculosMax" class="control-label"></label>
                </strong>
                <input asp-for="CantidadVehiculosMax" class="form-control" />
                <span asp-validation-for="CantidadVehiculosMax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="HoraApertura" class="control-label"></label>
                </strong>
                <input asp-for="HoraApertura" class="form-control" type="time" />
                <span asp-validation-for="HoraApertura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="HoraCierre" class="control-label"></label>
                </strong>
                <input asp-for="HoraCierre" class="form-control" type="time" />
                <span asp-validation-for="HoraCierre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="TarifaHora" class="control-label"></label>
                </strong>
                <input asp-for="TarifaHora" class="form-control" />
                <span asp-validation-for="TarifaHora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="TarifaMedia" class="control-label"></label>
                </strong>
                <input asp-for="TarifaMedia" class="form-control" />
                <span asp-validation-for="TarifaMedia" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <input id="btnAgregar" type="submit" value="Agregar" class="btn btn-primary" /> |
                <a asp-action="Index">Regresar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Proyecto 3/Proyecto 3/Views/Parqueos/Delete.cshtml
@model Proyecto_3.Models.Parqueo

@{
    ViewData["Title"] = "Delete";
}

<h1 style="text-align:center">ELIMINAR PARQUEO N° @Html.DisplayFor(model => model.Id)</h1>

<div>
    <h2>Datos del Parqueo</h2>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CantidadVehiculosMax)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CantidadVehiculosMax)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoraApertura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoraApertura)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoraCierre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoraCierre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TarifaHora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TarifaHora)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TarifaMedia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TarifaMedia)
        </dd>
    </dl>

    <h3>¿Desea proceder con la eliminación del registro del parqueo?</h3>
    
    <form asp-action="Delete" class="mt-4">
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar</a>
    </form>
</div>

Proyecto 3/Proyecto 3/Views/Parqueos/Details.cshtml
@model Proyecto_3.Models.Parqueo

@{
    ViewData["Title"] = "Details";
}

<h1 style="text-align:center">PARQUEO N° @Html.DisplayFor(model => model.Id)</h1>

<div>
    <h2>Datos del Parqueo</h2>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CantidadVehiculosMax)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CantidadVehiculosMax)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoraApertura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoraApertura)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoraCierre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoraCierre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TarifaHora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TarifaHora)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TarifaMedia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TarifaMedia)
        </dd>
    </dl>
</div>
<div>
    <button onclick="location.href='@Url.Action("Edit", "Parqueos", new { id = Model.Id })'" class="mb-3 btn-primary">Ir a actualizar</button> |
    <a asp-action="Index">Regresar</a>
</div>

Proyecto 3/Proyecto 3/Views/Parqueos/Edit.cshtml
@model Proyecto_3.Models.Parqueo

@{
    ViewData["Title"] = "Edit";
}

<h1 style="text-align:center">ACTUALIZAR PARQUEO N° @Html.DisplayFor(model => model.Id)</h1>

<h2>Datos del Empleado</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <strong>
                    @Html.DisplayNameFor(model => model.Id):
                </strong>
                @Html.DisplayFor(model => model.Id)
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="Nombre" class="control-label"></label>
                </strong>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="CantidadVehiculosMax" class="control-label"></label>
                </strong>
                <input asp-for="CantidadVehiculosMax" class="form-control" />
                <span asp-validation-for="CantidadVehiculosMax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="HoraApertura" class="control-label"></label>
                </strong>
                <input asp-for="HoraApertura" class="form-control" type="time" />
                <span asp-validation-for="HoraApertura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="HoraCierre" class="control-label"></label>
                </strong>
                <input asp-for="HoraCierre" class="form-control" type="time" />
                <span asp-validation-for="HoraCierre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="TarifaHora" class="control-label"></label>
                </strong>
                <input asp-for="TarifaHora" class="form-control" />
                <span asp-validation-for="TarifaHora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="TarifaMedia" class="control-label"></label>
                </strong>
                <input asp-for="TarifaMedia" class="form-control" />
                <span asp-validation-for="TarifaMedia" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <input type="submit" value="Actualizar" class="btn btn-primary" /> |
                <a asp-action="Index">Regresar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Proyecto 3/Proyecto 3/Views/Parqueos/Index.cshtml
@model IEnumerable<Proyecto_3.Models.Parqueo>

@{
    ViewData["Title"] = "Index";
}

<h1 style="text-align:center">INFORMACIÓN DEL PARQUEO</h1>

<p>
    <button onclick="location.href='@Url.Action("Create")'" class="mb-3 btn-primary">Agregar Parqueo</button>
    <br>
    <button onclick="location.href='@Url.Action("Details")' + '?id=' + document.getElementById('parqueoId').value" class="btn-primary" style="margin-right:25px" ">Buscar Parqueo</button>
    <input type="number" id="parqueoId" placeholder="Número de parqueo">

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantidadVehiculosMax)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HoraApertura)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HoraCierre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TarifaHora)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TarifaMedia)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CantidadVehiculosMax)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoraApertura)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoraCierre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TarifaHora)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TarifaMedia)
            </td>
            <td>
                @Html.ActionLink("Actualizar", "Edit", new { id=item.Id }) 
                <br>
                @Html.ActionLink("Eliminar", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>